services:
  component-portfolio-fe:
    build: .
    image: component-portfolio-fe:latest
    pull_policy: build
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
